#!/usr/bin/env python3
"""
test_playback_manifest.py — unit tests for kit_playback_manifest() (the GET
/api/kit_playback endpoint that feeds the browser Virtual-module engine).

Runs on the synthetic fixtures generated by tools/make_fixtures.py (no library
needed), then does a best-effort second pass over a real kit from F:\\STORAGE
read-only when that drive is present (skipped otherwise). Exit non-zero on failure.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import strike_remap as sr  # noqa: E402

FX = ROOT / 'tests' / 'fixtures'


def _by_layers(manifest):
    """Return (single-layer pad, dual-layer pad) from the synthetic kit."""
    single = dual = None
    for p in manifest['pads']:
        keys = set(p['layers'])
        if keys == {'a'} and p['layers']['a']['sin_rel'].endswith('single_zone.sin'):
            single = p
        elif keys == {'a', 'b'}:
            dual = p
    assert single, 'expected a single-layer pad (single_zone.sin on layer A)'
    assert dual, 'expected a dual-layer pad (multi_velocity A + single_zone B)'
    return single, dual


def test_structure_and_zones():
    sr.load_kit(str(FX / 'synthetic_kit.skt'))
    # Point the kit's instrument rel paths at the fixture .sin files.
    sr.state['avail'] = {
        'Fixtures/single_zone.sin':   FX / 'single_zone.sin',
        'Fixtures/multi_velocity.sin': FX / 'multi_velocity.sin',
    }
    m = sr.kit_playback_manifest()

    assert isinstance(m['rev'], int), 'rev must be present and int'
    assert m['kit'] == 'synthetic_kit.skt', m['kit']
    assert 'total_bytes' in m
    assert isinstance(m['pads'], list) and len(m['pads']) == len(sr.PAD_ORDER)

    single, dual = _by_layers(m)

    # single_zone.sin: one full-range mapping 1..127
    la = single['layers']['a']
    assert la['sin_rel'] == 'Fixtures/single_zone.sin'
    assert set(la['skt']) == {'level', 'pan', 'pitch', 'fine', 'decay', 'vel_min', 'vel_max'}
    assert set(la['sin']) == {'level', 'pan', 'semi', 'fine', 'decay', 'loop'}
    assert la['cycle_random'] in (0, 1)
    assert len(la['mappings']) == 1
    assert (la['mappings'][0]['vmin'], la['mappings'][0]['vmax']) == (1, 127)

    # dual pad: layer A = multi_velocity (3 zones), layer B = single_zone
    da, db = dual['layers']['a'], dual['layers']['b']
    zones = [(x['vmin'], x['vmax']) for x in da['mappings']]
    assert zones == [(1, 42), (43, 84), (85, 127)], zones
    assert db['sin_rel'] == 'Fixtures/single_zone.sin'

    # Fixture edits on the dual pad's payload must surface in skt params.
    assert da['skt']['pan'] == -10, da['skt']['pan']
    assert da['skt']['fine'] == 25, da['skt']['fine']
    assert da['skt']['pitch'] == -2, da['skt']['pitch']
    assert dual['midi_note'] == 38, dual['midi_note']
    # Layer B vel_min is the xfade threshold (set to 64 in the fixture); vel_max pinned 127.
    assert db['skt']['vel_min'] == 64, db['skt']['vel_min']
    assert db['skt']['vel_max'] == 127

    # mapping idx values are 0-based and contiguous (align with /api/wav idx).
    assert [x['idx'] for x in da['mappings']] == [0, 1, 2]
    print('  ok: structure, velocity zones, layer A/B, skt param passthrough')


def test_broken_paths_null():
    """The fixture WAVs don't exist on disk, so every wav_url must be null."""
    sr.load_kit(str(FX / 'synthetic_kit.skt'))
    sr.state['avail'] = {
        'Fixtures/single_zone.sin':   FX / 'single_zone.sin',
        'Fixtures/multi_velocity.sin': FX / 'multi_velocity.sin',
    }
    m = sr.kit_playback_manifest()
    urls = [mp['wav_url'] for p in m['pads'] for lyr in p['layers'].values()
            for mp in lyr.get('mappings', [])]
    assert urls, 'expected some mappings'
    assert all(u is None for u in urls), 'unresolved WAVs must yield wav_url=None'
    assert m['total_bytes'] == 0
    print('  ok: broken WAV paths -> wav_url null, total_bytes 0')


def test_wav_url_alignment(monkeypatch_target=None):
    """When WAVs resolve, wav_url must be /api/wav?sin=<enc>&idx=<i> and total_bytes
    must sum distinct URLs. We stub find_wav_for_sin_idx with a real temp file."""
    import tempfile
    from urllib.parse import quote
    sr.load_kit(str(FX / 'synthetic_kit.skt'))
    sr.state['avail'] = {
        'Fixtures/single_zone.sin':   FX / 'single_zone.sin',
        'Fixtures/multi_velocity.sin': FX / 'multi_velocity.sin',
    }
    tmp = Path(tempfile.mkdtemp()) / 'stub.wav'
    tmp.write_bytes(b'\x00' * 100)  # 100-byte stand-in
    orig = sr.find_wav_for_sin_idx
    sr.find_wav_for_sin_idx = lambda sin_rel, idx: tmp
    try:
        m = sr.kit_playback_manifest()
    finally:
        sr.find_wav_for_sin_idx = orig

    single, dual = _by_layers(m)
    da = dual['layers']['a']
    for i, mp in enumerate(da['mappings']):
        expected = '/api/wav?sin=' + quote('Fixtures/multi_velocity.sin') + '&idx=' + str(i)
        assert mp['wav_url'] == expected, (mp['wav_url'], expected)
        assert mp['size'] == 100
    # total_bytes counts distinct URLs only: single_zone idx0 (1) + multi idx0..2 (3) = 4 files
    assert m['total_bytes'] == 400, m['total_bytes']
    print('  ok: wav_url idx alignment + total_bytes dedup/sum')


def _die_on_nonascii():
    """Force stdout to ASCII-safe so Windows cp1252 consoles never crash on output."""
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:  # noqa: BLE001
        pass


def test_real_kit_smoke():
    """Best-effort: build a manifest from a real kit on F:\\STORAGE (read-only).
    Skipped when the drive/library is absent (e.g. CI)."""
    storage = Path('F:/STORAGE')
    if not storage.is_dir():
        print('  skip: F:\\STORAGE not present')
        return
    kits = list(storage.rglob('*.skt'))[:1] or list(storage.rglob('*.SKT'))[:1]
    if not kits:
        print('  skip: no .skt found under F:\\STORAGE')
        return
    try:
        sr.refresh_available()
        sr.load_kit(str(kits[0]))
        m = sr.kit_playback_manifest()
    except Exception as e:  # noqa: BLE001
        print(f'  skip: real-kit pass errored ({e})')
        return
    assert isinstance(m['pads'], list) and m['pads'], 'real kit produced no pads'
    assert isinstance(m['rev'], int)
    # sanity: any assigned layer has the documented shape
    for p in m['pads']:
        for lyr in p['layers'].values():
            if 'error' in lyr:
                continue
            assert 'skt' in lyr and 'mappings' in lyr
    print(f'  ok: real kit {kits[0].name} → {len(m["pads"])} pads')


def main():
    _die_on_nonascii()
    tests = [test_structure_and_zones, test_broken_paths_null,
             test_wav_url_alignment, test_real_kit_smoke]
    for t in tests:
        print(f'- {t.__name__}')
        t()
    print(f'\nAll {len(tests)} playback-manifest tests passed.')


if __name__ == '__main__':
    main()
